### ISSUE TITLE
Trackpad not working

### ISSUE THREAD

**Issue by psanford** [tpwrules/nixos-m1#14]
Thanks for this config! 

Things are working for me except trackpad movements are not being detected. Trackpad clicks do seem to work though. I had previously installed Asahi+Arch and the trackpad worked correctly there.

This is with a new m2 air. It sounds like there were some changes for the M2 trackpad:  https://asahilinux.org/2022/07/july-2022-release/ is there something that needs to be updated to get the trackpad working?

**Comment by tpwrules** [comment]
Do you have libinput enabled in your configuration? I.e. `services.xserver.libinput.enable = true;`. I've had similar symptoms without this on some machines before.

I assume the official Asahi installer would have extracted the correct firmware for the trackpad but it wouldn't hurt to use `asahi-fwextract` as described in the installation guide. 

Otherwise, I suppose it's possible there's a kernel config issue, but I didn't see any changes to the official config that would correlate to this.

**Comment by psanford** [comment]
Ah, it was that :facepalm: . I had copied a config from a different laptop that had disabled libinput for the synaptics driver and I removed the synaptics specific config but missed that libinput was still disabled.

Thanks!
