### ISSUE TITLE
Can't get Bluetooth to work

### ISSUE THREAD

**Issue by epetousis** [tpwrules/nixos-m1#18]
I'm running a 2020 M1 MacBook Air, but am having trouble getting bluetooth.service to start with the latest kernel that was pushed here. I don't think Bluetooth is loading at all (`/sys/class/bluetooth` is missing), and I'm not quite sure why - I'd assume firmware isn't the issue as WiFi is working fine. I didn't spot any issues about Bluetooth, is this something that requires further work to support in NixOS, or have I just messed something up? Happy to provide logs if they're of any use.

**Comment by tpwrules** [comment]
Looks like the last time Bluetooth worked was nixos-m1 commit `8b54e3b`. I'm not sure exactly what happened in later versions but I checked on my M1 Max MBP. You will have to cherry-pick nixos-m1 commit `523ec0b` if you want to build it with recent nixpkgs versions.

It's probable it's an upstream issue because not much changed on my end to break it. The Asahi project has not had an official non-dev kernel release in quite a while now which is why I haven't been releasing much either but if it fixes Bluetooth then that's a good reason to make one. I'll look into it but if you want Bluetooth now I suggest using an older nixos-m1 commit (or just the kernel) as described above.

**Comment by epetousis** [comment]
Definitely not an urgent requirement for me, was more just confused as to why it wasn't working. Appreciate you looking into it though, and apologies for not thinking to bisect the module myself (didn't realise it was previously working).
