### ISSUE TITLE
`cryptsetup` missing?

### ISSUE THREAD

**Issue by WhyNotHugo** [tpwrules/nixos-m1#4]
I've generated an installer with [the instructions](https://github.com/tpwrules/nixos-m1/blob/main/docs/uefi-standalone.md#kernel-and-bootstrap-installer) on this repo, and then booted into U-Boot and then the image itself off a USB drive.

However, the installation media seems to be missing `cryptsetup`, so I can't mount (nor re-format) the existing partition on my device.

Can I somehow build an image that includes the additions from this repo _and_ the default ISO installer tools?

**Comment by WhyNotHugo** [comment]
Figured it out. :)

**Comment by WhyNotHugo** [comment]
I tried adding `cryptsetup` to `environment.systemPackages`, but looks like it's missing some dependencies or flags...

```
device-mapper: table: 253:0: crypt: unknown target type
device-mapper: ioctl: error adding target to table
device-mapper:  reload ioctl on root (253:0) failed: Invalid argument
```

So I guess it's back to the original question: can I somehow make sure the ISO has all the tools the default installer ISO would include?

**Comment by WhyNotHugo** [comment]
Hm, apparently this is due to `dm-crypt` module being missing. The Asahi kernel _does_ include `dm-crypt` tho.

**Comment by WhyNotHugo** [comment]
I tried replacing https://github.com/tpwrules/nixos-m1/blob/main/nix/m1-support/kernel/config with Asahi's version: https://github.com/AsahiLinux/PKGBUILDs/blob/main/linux-asahi/config.

That did not work, booting the ISO doesn't work. Obviously the Asahi/Arch kernel has _other_ differences that don't work with the Nix loader.

**Comment by tpwrules** [comment]
The default installer ISO tools are [listed here](https://github.com/NixOS/nixpkgs/blob/1d370bd07399fb52cea6badfbffbc90ac9b0f8f0/nixos/modules/profiles/base.nix#L9). Everything that goes in the ISO has to be cross-compiled by the user if they are building on x86_64 (which the Github Actions builder uses), so I chose to remove anything that wasn't absolutely essential to doing a base install and/or getting connected to the internet to download more. That's why it's a "bootstrap" ISO, it doesn't even have enough to be counted as "minimal".

That said, it looks like `cryptsetup` was already included as part of `systemd` but not in the path, so I would be totally fine with adding it for user usage. But you are right, the kernel config is also pretty minimal and doesn't support encryption anyway.

**Comment by psanford** [comment]
I was able to get luks encryption working with the following additions (this isn't necessarily the minimal set of changes necessary):

```
 boot.initrd.availableKernelModules = [ "usb_storage" "usbhid"  "dm-crypt" "xts" "encrypted_keys" "ext4" "dm-snapshot" ];
  boot.initrd.kernelModules = [ "usb_storage" "usbhid"  "dm-crypt" "xts" "encrypted_keys" "ext4" "dm-snapshot" ];
```

kernel config additions:
```
+CONFIG_DM_SNAPSHOT=m
+CONFIG_KEYS=y
+CONFIG_ENCRYPTED_KEYS=m
+CONFIG_TRUSTED_KEYS=m
```
